import { create } from "zustand";
import { SurveyType } from "./surveyStore.type";

const useSurveyStore = create<SurveyType>((set) => ({
  surveys: [
    {
      remainTime: "",
      title: "설문지 제목1",
      startTime: "2023-07-26-17-30",
      endTime: "2023-07-30-21-20",
      headCount: "10",
      closedHeadCount: "100",
      nickname: "닉네임abc",
      type: "타임어택",
      probability: "27%",
      giveaways: "coffee",
    },
    {
      remainTime: "",
      title: "설문지 제목2",
      startTime: "2023-07-27-10-45",
      endTime: "2023-07-30-11-25",
      headCount: "15",
      closedHeadCount: "50",
      nickname: "닉네임def",
      type: "즉시당첨",
      probability: "34%",
      giveaways: "chicken",
    },
    {
      remainTime: "",
      title: "설문지 제목3",
      startTime: "2023-07-28-14-00",
      endTime: "2023-08-01-15-30",
      headCount: "20",
      closedHeadCount: "80",
      nickname: "닉네임ghi",
      type: "타임어택",
      probability: "45%",
      giveaways: "coffee",
    },
    {
      remainTime: "",
      title: "설문지 제목4",
      startTime: "2023-07-30-11-20",
      endTime: "2023-08-03-12-30",
      headCount: "30",
      closedHeadCount: "60",
      nickname: "닉네임mno",
      type: "타임어택",
      probability: "47%",
      giveaways: "chicken",
    },
    {
      remainTime: "",
      title: "설문지 제목5",
      startTime: "2023-07-29-09-10",
      endTime: "2023-08-02-10-50",
      headCount: "25",
      closedHeadCount: "70",
      nickname: "닉네임jkl",
      type: "즉시당첨",
      probability: "36%",
      giveaways: "coffee",
    },
    // {
    //   remainTime: "",
    //   title: "설문지 제목6",
    //   startTime: "2023-07-31-13-30",
    //   endTime: "2023-08-04-14-10",
    //   headCount: "35",
    //   closedHeadCount: "55",
    //   nickname: "닉네임pqr",
    //   type: "즉시당첨",
    //   probability: "38%",
    //   giveaways: "chicken",
    // },
    // {
    //   remainTime: "",
    //   title: "설문지 제목7",
    //   startTime: "2023-08-01-15-40",
    //   endTime: "2023-08-05-16-00",
    //   headCount: "40",
    //   closedHeadCount: "45",
    //   nickname: "닉네임stu",
    //   type: "타임어택",
    //   probability: "50%",
    //   giveaways: "chicken",
    // },
    // {
    //   remainTime: "",
    //   title: "설문지 제목8",
    //   startTime: "2023-08-02-17-50",
    //   endTime: "2023-08-06-18-20",
    //   headCount: "45",
    //   closedHeadCount: "35",
    //   nickname: "닉네임vwx",
    //   type: "즉시당첨",
    //   probability: "42%",
    //   giveaways: "coffee",
    // },
  ],
}));

export default useSurveyStore;
